namespace: philobiblus-mlops

mlflow:
  image:
    repository: ghcr.io/mlflow/mlflow
    tag: v2.10.0
  replicaCount: 1
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
      ephemeral-storage: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"
      ephemeral-storage: "2Gi"

trainer:
  image:
    repository: us-central1-docker.pkg.dev/PROJECT_ID/philobiblus/training
    tag: latest
  schedule: "0 20 * * *"
  suspend: true
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
      ephemeral-storage: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
      ephemeral-storage: "4Gi"
  db_uri: "" # injected via secret sync or env
  mlops_bucket: "" # injected via value
