{{- if .Values.monitoring.podMonitoring.enabled }}
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: {{ include "philobiblus.fullname" . }}-backend
  labels:
    {{- include "philobiblus.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "philobiblus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.podMonitoring.interval }}
{{- if .Values.recommendation.enabled }}
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: {{ include "philobiblus.fullname" . }}-recommendation
  labels:
    {{- include "philobiblus.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "philobiblus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: recommendation
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.podMonitoring.interval }}
{{- end }}
{{- end }}
