{{- if .Values.serviceAccounts.backend.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "philobiblus.backendServiceAccountName" . }}
  labels:
    {{- include "philobiblus.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- with .Values.serviceAccounts.backend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- if .Values.serviceAccounts.recommendation.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "philobiblus.recommendationServiceAccountName" . }}
  labels:
    {{- include "philobiblus.labels" . | nindent 4 }}
    app.kubernetes.io/component: recommendation
  {{- with .Values.serviceAccounts.recommendation.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- if .Values.serviceAccounts.seed.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "philobiblus.seedServiceAccountName" . }}
  labels:
    {{- include "philobiblus.labels" . | nindent 4 }}
    app.kubernetes.io/component: seed
  {{- with .Values.serviceAccounts.seed.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
