#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib.sh"

require_commands terraform gcloud

PROJECT_ID="$(project_id)"
STATE_BUCKET_NAME="$(state_bucket_name)"

cat >"$GKE_PLATFORM_DIR/terraform.tfvars" <<EOF
project_id        = "$PROJECT_ID"
region            = "$REGION"
environment       = "$ENVIRONMENT"
state_bucket_name = "$STATE_BUCKET_NAME"
protect_cluster   = true
release_channel   = "REGULAR"
EOF

chmod 600 "$GKE_PLATFORM_DIR/terraform.tfvars"
log "Wrote ignored GKE platform configuration."

if [[ -d "$GKE_APP_DIR" ]]; then
  log "GKE app module detected; app configuration will be generated by 30-app-apply.sh."
fi
