{{- if .Values.monitoring.podMonitoring }}
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: philobiblus-mlops
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mlflow
  endpoints:
    - port: 5000
      interval: 30s
{{- end }}
