apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.mlflow.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ required "mlflow.serviceAccount.gcpServiceAccount is required" .Values.mlflow.serviceAccount.gcpServiceAccount | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.trainer.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ required "trainer.serviceAccount.gcpServiceAccount is required" .Values.trainer.serviceAccount.gcpServiceAccount | quote }}
