apiVersion: v1
kind: ServiceAccount
metadata:
  name: philobiblus-mlflow
  namespace: {{ .Values.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: "philobiblus-mlflow@${GCP_PROJECT_ID}.iam.gserviceaccount.com"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: philobiblus-trainer
  namespace: {{ .Values.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: "philobiblus-trainer@${GCP_PROJECT_ID}.iam.gserviceaccount.com"
