apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: philobiblus-trainer-promoter
  namespace: {{ .Values.appNamespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.trainer.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: philobiblus-trainer-promoter
  apiGroup: rbac.authorization.k8s.io
